name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          # GitHub 사용자 이름 및 레포지토리 이름 소문자로 변환
          REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPOSITORY_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          
          # Docker 이미지 빌드 및 푸시
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ghcr.io/$REPOSITORY_OWNER/$REPOSITORY_NAME:latest .

  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > key.pem
          chmod 600 key.pem

      - name: SSH into EC2 and pull/run container
        run: |
          # GitHub 사용자 이름 및 레포지토리 이름 소문자로 변환
          REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPOSITORY_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          # 환경변수 준비 (secrets에 해당 값들을 넣어두어야 값이 똑바로 읽어와진다!)
          HOST=${{ secrets.EC2_HOST }}
          USER=${{ secrets.EC2_USER }}

          # EC2 서버 접속 후 Docker 명령 실행
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "docker rm -f $REPOSITORY_NAME || true"

          # GHCR로부터 최신 이미지 pull
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}"
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "docker pull ghcr.io/$REPOSITORY_OWNER/$REPOSITORY_NAME:latest"

          # 새로운 컨테이너 실행 (포트 매핑)
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "docker run -d --name $REPOSITORY_NAME -p 3000:3000 ghcr.io/$REPOSITORY_OWNER/$REPOSITORY_NAME:latest"
